"""esquema inicial

Revision ID: 0001
Revises: 
Create Date: 2026-10-08 23:21:17.594214
"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql


revision: str = '0001'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_log',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('actor_user_id', sa.Uuid(), nullable=True),
    sa.Column('actor_type', sa.String(length=20), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('entity_type', sa.String(length=80), nullable=False),
    sa.Column('entity_id', sa.String(length=80), nullable=False),
    sa.Column('ip', sa.String(length=64), nullable=True),
    sa.Column('request_id', sa.String(length=64), nullable=True),
    sa.Column('diff', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('prev_hash', sa.String(length=64), nullable=False),
    sa.Column('hash', sa.String(length=64), nullable=False),
    sa.CheckConstraint("actor_type IN ('user', 'system', 'contact', 'webhook')", name=op.f('ck_audit_log_actor_type')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_log'))
    )
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.create_index('ix_audit_log_action', ['action'], unique=False)
        batch_op.create_index('ix_audit_log_tenant_id', ['tenant_id'], unique=False)
        batch_op.create_index('ix_audit_log_ts', ['ts'], unique=False)

    op.create_table('niche_templates',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('niche', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_niche_templates'))
    )
    with op.batch_alter_table('niche_templates', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_niche_templates_niche'), ['niche'], unique=False)

    op.create_table('offers',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('code', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('discount_type', sa.String(length=40), nullable=False),
    sa.Column('value', sa.Integer(), nullable=False),
    sa.Column('max_redemptions', sa.Integer(), nullable=True),
    sa.Column('redeemed', sa.Integer(), nullable=False),
    sa.Column('valid_until', sa.Date(), nullable=True),
    sa.Column('applies_to_plan_codes', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('conditions', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("discount_type IN ('setup_pct', 'monthly_pct', 'monthly_fixed_months_free')", name=op.f('ck_offers_discount_type')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_offers')),
    sa.UniqueConstraint('code', name=op.f('uq_offers_code'))
    )
    op.create_table('plans',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('code', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('setup_fee_cop', sa.Integer(), nullable=False),
    sa.Column('monthly_fee_cop', sa.Integer(), nullable=False),
    sa.Column('limits', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('features', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('sort', sa.Integer(), nullable=False),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_plans')),
    sa.UniqueConstraint('code', name=op.f('uq_plans_code'))
    )
    op.create_table('suppression_list',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('phone_hash', sa.String(length=64), nullable=False),
    sa.Column('reason', sa.String(length=20), nullable=False),
    sa.Column('scope', sa.String(length=10), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=True),
    sa.Column('tenant_key', sa.String(length=36), nullable=False),
    sa.Column('source_lead_id', sa.Uuid(), nullable=True),
    sa.Column('evidence', sa.Text(), nullable=False),
    sa.Column('suppressed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("reason IN ('opt_out', 'complaint', 'manual', 'bounced')", name=op.f('ck_suppression_list_reason')),
    sa.CheckConstraint("scope IN ('global', 'tenant', 'agency')", name=op.f('ck_suppression_list_scope')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_suppression_list'))
    )
    with op.batch_alter_table('suppression_list', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_suppression_list_phone_hash'), ['phone_hash'], unique=False)
        batch_op.create_index('uq_suppression_phone_scope', ['phone_hash', 'scope', 'tenant_key'], unique=True)

    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('failed_logins', sa.Integer(), nullable=False),
    sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('totp_secret_enc', sa.LargeBinary(), nullable=True),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("role IN ('owner', 'admin', 'operator')", name=op.f('ck_users_role')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('email', name=op.f('uq_users_email'))
    )
    op.create_table('webhook_events',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('provider', sa.String(length=20), nullable=False),
    sa.Column('provider_sid', sa.String(length=64), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('status_value', sa.String(length=30), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=True),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('payload_hash', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.CheckConstraint("kind IN ('inbound', 'status')", name=op.f('ck_webhook_events_kind')),
    sa.CheckConstraint("status IN ('received', 'processed', 'ignored', 'failed')", name=op.f('ck_webhook_events_status')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_webhook_events')),
    sa.UniqueConstraint('provider', 'kind', 'provider_sid', 'status_value', name='uq_webhook_events_dedupe')
    )
    with op.batch_alter_table('webhook_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_webhook_events_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('lead_sources',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('label', sa.String(length=200), nullable=False),
    sa.Column('params', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('stats', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("kind IN ('places_api', 'csv_import', 'manual')", name=op.f('ck_lead_sources_kind')),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_lead_sources_created_by_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_lead_sources'))
    )
    op.create_table('sessions',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('csrf_token', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('absolute_expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ip', sa.String(length=64), nullable=True),
    sa.Column('user_agent', sa.String(length=300), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_sessions_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sessions'))
    )
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.create_index('ix_sessions_expires_at', ['expires_at'], unique=False)
        batch_op.create_index('ix_sessions_user_id', ['user_id'], unique=False)

    op.create_table('tenants',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('slug', sa.String(length=80), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('niche', sa.String(length=30), nullable=False),
    sa.Column('niche_template_id', sa.Uuid(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('address', sa.String(length=300), nullable=False),
    sa.Column('timezone', sa.String(length=50), nullable=False),
    sa.Column('website_url', sa.String(length=500), nullable=True),
    sa.Column('instagram_url', sa.String(length=500), nullable=True),
    sa.Column('phone_contact', sa.String(length=30), nullable=True),
    sa.Column('owner_name', sa.String(length=200), nullable=False),
    sa.Column('is_demo', sa.Boolean(), nullable=False),
    sa.Column('dpa_version', sa.String(length=20), nullable=True),
    sa.Column('dpa_accepted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("niche IN ('dentista', 'clinica_estetica', 'taller', 'restaurante', 'otro')", name=op.f('ck_tenants_niche')),
    sa.CheckConstraint("status IN ('draft', 'building', 'review', 'active', 'paused', 'offboarded')", name=op.f('ck_tenants_status')),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_tenants_created_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['niche_template_id'], ['niche_templates.id'], name=op.f('fk_tenants_niche_template_id_niche_templates'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tenants')),
    sa.UniqueConstraint('slug', name=op.f('uq_tenants_slug'))
    )
    with op.batch_alter_table('tenants', schema=None) as batch_op:
        batch_op.create_index('ix_tenants_status', ['status'], unique=False)

    op.create_table('bot_configs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('system_prompt', sa.Text(), nullable=False),
    sa.Column('booking_rules', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('guardrails', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('templates', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('config', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('generation_meta', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('source_inputs', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('model', sa.String(length=80), nullable=False),
    sa.Column('generated_by', sa.String(length=20), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('published_by', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.CheckConstraint("generated_by IN ('factory', 'manual')", name=op.f('ck_bot_configs_generated_by')),
    sa.CheckConstraint("status IN ('draft', 'published', 'archived')", name=op.f('ck_bot_configs_status')),
    sa.ForeignKeyConstraint(['published_by'], ['users.id'], name=op.f('fk_bot_configs_published_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_bot_configs_tenant_id_tenants'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_bot_configs')),
    sa.UniqueConstraint('tenant_id', 'version', name='uq_bot_configs_tenant_version')
    )
    with op.batch_alter_table('bot_configs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_bot_configs_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index('uq_bot_configs_one_published', ['tenant_id'], unique=True, sqlite_where=sa.text("status = 'published'"), postgresql_where=sa.text("status = 'published'"))

    op.create_table('calendar_connections',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('provider', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('google_calendar_id', sa.String(length=300), nullable=True),
    sa.Column('google_account_email_enc', sa.LargeBinary(), nullable=True),
    sa.Column('scopes', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('sync_token_enc', sa.LargeBinary(), nullable=True),
    sa.Column('watch_channel_id', sa.String(length=100), nullable=True),
    sa.Column('watch_resource_id', sa.String(length=100), nullable=True),
    sa.Column('watch_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_sync_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.CheckConstraint("provider IN ('google', 'local')", name=op.f('ck_calendar_connections_provider')),
    sa.CheckConstraint("status IN ('active', 'needs_reauth', 'revoked', 'error')", name=op.f('ck_calendar_connections_status')),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_calendar_connections_tenant_id_tenants'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_calendar_connections'))
    )
    with op.batch_alter_table('calendar_connections', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_calendar_connections_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index('uq_calendar_connections_active', ['tenant_id'], unique=True, sqlite_where=sa.text("status <> 'revoked'"), postgresql_where=sa.text("status <> 'revoked'"))

    op.create_table('channel_accounts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('channel', sa.String(length=20), nullable=False),
    sa.Column('provider', sa.String(length=20), nullable=False),
    sa.Column('phone_e164', sa.String(length=20), nullable=False),
    sa.Column('twilio_messaging_service_sid', sa.String(length=40), nullable=True),
    sa.Column('twilio_subaccount_sid', sa.String(length=40), nullable=True),
    sa.Column('whatsapp_sender_status', sa.String(length=20), nullable=True),
    sa.Column('voice_enabled', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('webhook_token_hash', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.CheckConstraint("channel IN ('whatsapp', 'voice')", name=op.f('ck_channel_accounts_channel')),
    sa.CheckConstraint("whatsapp_sender_status IS NULL OR whatsapp_sender_status IN ('sandbox', 'pending', 'approved', 'rejected')", name=op.f('ck_channel_accounts_whatsapp_sender_status')),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_channel_accounts_tenant_id_tenants'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_channel_accounts')),
    sa.UniqueConstraint('phone_e164', name=op.f('uq_channel_accounts_phone_e164'))
    )
    with op.batch_alter_table('channel_accounts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_channel_accounts_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('contacts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('phone_hash', sa.String(length=64), nullable=False),
    sa.Column('phone_enc', sa.LargeBinary(), nullable=True),
    sa.Column('display_name_enc', sa.LargeBinary(), nullable=True),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('opted_out', sa.Boolean(), nullable=False),
    sa.Column('opted_out_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('opt_out_source', sa.String(length=20), nullable=True),
    sa.Column('opt_out_keyword', sa.String(length=60), nullable=True),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('erased_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.CheckConstraint("opt_out_source IS NULL OR opt_out_source IN ('keyword', 'manual', 'complaint')", name=op.f('ck_contacts_opt_out_source')),
    sa.CheckConstraint("source IN ('inbound', 'import', 'demo')", name=op.f('ck_contacts_source')),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_contacts_tenant_id_tenants'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_contacts')),
    sa.UniqueConstraint('tenant_id', 'phone_hash', name='uq_contacts_tenant_phone_hash')
    )
    with op.batch_alter_table('contacts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_contacts_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('faqs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('answer', sa.Text(), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('needs_review', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('sort', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.CheckConstraint("source IN ('template', 'scrape', 'manual')", name=op.f('ck_faqs_source')),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_faqs_tenant_id_tenants'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_faqs'))
    )
    with op.batch_alter_table('faqs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_faqs_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('kb_documents',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('source_url', sa.String(length=1000), nullable=True),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_kb_documents_tenant_id_tenants'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_kb_documents')),
    sa.UniqueConstraint('tenant_id', 'content_hash', name='uq_kb_documents_tenant_hash')
    )
    with op.batch_alter_table('kb_documents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_kb_documents_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('leads',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('source_id', sa.Uuid(), nullable=True),
    sa.Column('place_id', sa.String(length=200), nullable=True),
    sa.Column('maps_url', sa.String(length=500), nullable=True),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('name_key', sa.String(length=300), nullable=False),
    sa.Column('niche', sa.String(length=30), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('address', sa.String(length=300), nullable=False),
    sa.Column('phone_e164', sa.String(length=20), nullable=True),
    sa.Column('phone_hash', sa.String(length=64), nullable=True),
    sa.Column('phone_enc', sa.LargeBinary(), nullable=True),
    sa.Column('phone_type', sa.String(length=10), nullable=True),
    sa.Column('website', sa.String(length=500), nullable=True),
    sa.Column('website_domain', sa.String(length=200), nullable=True),
    sa.Column('instagram', sa.String(length=300), nullable=True),
    sa.Column('instagram_handle', sa.String(length=100), nullable=True),
    sa.Column('rating', sa.Numeric(precision=2, scale=1), nullable=True),
    sa.Column('review_count', sa.Integer(), nullable=True),
    sa.Column('business_status', sa.String(length=30), nullable=True),
    sa.Column('price_level', sa.SmallInteger(), nullable=True),
    sa.Column('hours', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('signals', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('score', sa.SmallInteger(), nullable=False),
    sa.Column('score_breakdown', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('score_version', sa.Integer(), nullable=False),
    sa.Column('tags', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('stage', sa.String(length=20), nullable=False),
    sa.Column('disposition', sa.String(length=20), nullable=False),
    sa.Column('owner_user_id', sa.Uuid(), nullable=True),
    sa.Column('converted_tenant_id', sa.Uuid(), nullable=True),
    sa.Column('demo_tenant_id', sa.Uuid(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('last_contacted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('next_action_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("disposition IN ('activo', 'perdido', 'no_contactar')", name=op.f('ck_leads_disposition')),
    sa.CheckConstraint("phone_type IS NULL OR phone_type IN ('mobile', 'landline', 'unknown')", name=op.f('ck_leads_phone_type')),
    sa.CheckConstraint("stage IN ('nuevo', 'prueba_secreta', 'contactado', 'demo', 'cerrado')", name=op.f('ck_leads_stage')),
    sa.ForeignKeyConstraint(['converted_tenant_id'], ['tenants.id'], name=op.f('fk_leads_converted_tenant_id_tenants'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['demo_tenant_id'], ['tenants.id'], name=op.f('fk_leads_demo_tenant_id_tenants'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], name=op.f('fk_leads_owner_user_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_id'], ['lead_sources.id'], name=op.f('fk_leads_source_id_lead_sources'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_leads')),
    sa.UniqueConstraint('place_id', name=op.f('uq_leads_place_id'))
    )
    with op.batch_alter_table('leads', schema=None) as batch_op:
        batch_op.create_index('ix_leads_name_key', ['name_key'], unique=False)
        batch_op.create_index('ix_leads_niche_city', ['niche', 'city'], unique=False)
        batch_op.create_index('ix_leads_stage_score', ['stage', 'score'], unique=False)
        batch_op.create_index('ix_leads_website_domain', ['website_domain'], unique=False)
        batch_op.create_index('uq_leads_phone_hash_active', ['phone_hash'], unique=True, sqlite_where=sa.text("phone_hash IS NOT NULL AND disposition <> 'perdido'"), postgresql_where=sa.text("phone_hash IS NOT NULL AND disposition <> 'perdido'"))

    op.create_table('llm_usage',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('purpose', sa.String(length=30), nullable=False),
    sa.Column('model', sa.String(length=80), nullable=False),
    sa.Column('tokens_in', sa.Integer(), nullable=False),
    sa.Column('tokens_out', sa.Integer(), nullable=False),
    sa.Column('cache_read', sa.Integer(), nullable=False),
    sa.Column('cost_usd', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_llm_usage_tenant_id_tenants'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_llm_usage'))
    )
    with op.batch_alter_table('llm_usage', schema=None) as batch_op:
        batch_op.create_index('ix_llm_usage_tenant_created', ['tenant_id', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_llm_usage_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('message_templates',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('scope', sa.String(length=10), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=30), nullable=False),
    sa.Column('category', sa.String(length=20), nullable=True),
    sa.Column('niche', sa.String(length=30), nullable=True),
    sa.Column('language', sa.String(length=10), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('variables', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('twilio_content_sid', sa.String(length=40), nullable=True),
    sa.Column('approval_status', sa.String(length=20), nullable=False),
    sa.Column('approved', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("approval_status IN ('draft', 'submitted', 'approved', 'rejected')", name=op.f('ck_message_templates_approval_status')),
    sa.CheckConstraint("category IS NULL OR category IN ('utility', 'marketing', 'authentication')", name=op.f('ck_message_templates_category')),
    sa.CheckConstraint("kind IN ('pitch', 'seguimiento', 'optout_confirm', 'prueba_secreta_hint', 'general')", name=op.f('ck_message_templates_kind')),
    sa.CheckConstraint("scope IN ('outreach', 'tenant')", name=op.f('ck_message_templates_scope')),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_message_templates_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_message_templates')),
    sa.UniqueConstraint('name', 'version', name='uq_message_templates_name_version')
    )
    with op.batch_alter_table('message_templates', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_message_templates_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('resources',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('key', sa.String(length=60), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('kind', sa.String(length=40), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_resources_tenant_id_tenants'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_resources')),
    sa.UniqueConstraint('tenant_id', 'key', name='uq_resources_tenant_key')
    )
    with op.batch_alter_table('resources', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_resources_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('services',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('price_cop', sa.Integer(), nullable=True),
    sa.Column('price_note', sa.String(length=200), nullable=False),
    sa.Column('duration_min', sa.Integer(), nullable=False),
    sa.Column('requires_deposit', sa.Boolean(), nullable=False),
    sa.Column('needs_review', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('sort', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_services_tenant_id_tenants'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_services'))
    )
    with op.batch_alter_table('services', schema=None) as batch_op:
        batch_op.create_index('ix_services_tenant_active', ['tenant_id', 'is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_services_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('subscriptions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('plan_id', sa.Uuid(), nullable=False),
    sa.Column('offer_id', sa.Uuid(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('current_period_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('custom_monthly_fee_cop', sa.Integer(), nullable=True),
    sa.Column('guarantee_until', sa.Date(), nullable=True),
    sa.Column('guarantee_status', sa.String(length=20), nullable=True),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.CheckConstraint("guarantee_status IS NULL OR guarantee_status IN ('vigente', 'reclamada', 'vencida')", name=op.f('ck_subscriptions_guarantee_status')),
    sa.CheckConstraint("status IN ('trial', 'active', 'past_due', 'cancelled')", name=op.f('ck_subscriptions_status')),
    sa.ForeignKeyConstraint(['offer_id'], ['offers.id'], name=op.f('fk_subscriptions_offer_id_offers'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['plan_id'], ['plans.id'], name=op.f('fk_subscriptions_plan_id_plans'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_subscriptions_tenant_id_tenants'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_subscriptions'))
    )
    with op.batch_alter_table('subscriptions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_subscriptions_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index('ix_subscriptions_tenant_status', ['tenant_id', 'status'], unique=False)

    op.create_table('tenant_profiles',
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('hours', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('tone', sa.Text(), nullable=False),
    sa.Column('languages', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('handoff_phone', sa.String(length=30), nullable=True),
    sa.Column('scraped_summary', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_tenant_profiles_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('tenant_id', name=op.f('pk_tenant_profiles'))
    )
    op.create_table('tenant_secrets',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('kind', sa.String(length=40), nullable=False),
    sa.Column('ciphertext', sa.LargeBinary(), nullable=False),
    sa.Column('nonce', sa.LargeBinary(), nullable=False),
    sa.Column('key_version', sa.String(length=20), nullable=False),
    sa.Column('last4', sa.String(length=4), nullable=False),
    sa.Column('rotated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.CheckConstraint("kind IN ('twilio_auth_token', 'twilio_sid', 'google_oauth_refresh', 'google_calendar_id', 'custom_api')", name=op.f('ck_tenant_secrets_kind')),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_tenant_secrets_tenant_id_tenants'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tenant_secrets')),
    sa.UniqueConstraint('tenant_id', 'kind', name='uq_tenant_secrets_tenant_kind')
    )
    with op.batch_alter_table('tenant_secrets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tenant_secrets_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('usage_counters',
    sa.Column('period', sa.String(length=7), nullable=False),
    sa.Column('conversations', sa.Integer(), nullable=False),
    sa.Column('messages_in', sa.Integer(), nullable=False),
    sa.Column('messages_out', sa.Integer(), nullable=False),
    sa.Column('llm_tokens_in', sa.Integer(), nullable=False),
    sa.Column('llm_tokens_out', sa.Integer(), nullable=False),
    sa.Column('templates_sent', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_usage_counters_tenant_id_tenants'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('tenant_id', 'period', name='pk_usage_counters')
    )
    with op.batch_alter_table('usage_counters', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_usage_counters_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('appointments',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('contact_id', sa.Uuid(), nullable=True),
    sa.Column('service_id', sa.Uuid(), nullable=True),
    sa.Column('resource_id', sa.Uuid(), nullable=True),
    sa.Column('resource_key', sa.String(length=60), nullable=False),
    sa.Column('starts_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ends_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('idempotency_key', sa.String(length=100), nullable=True),
    sa.Column('hold_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('google_event_id', sa.String(length=200), nullable=True),
    sa.Column('google_event_etag', sa.String(length=200), nullable=True),
    sa.Column('sync_status', sa.String(length=20), nullable=False),
    sa.Column('cancelled_by', sa.String(length=20), nullable=True),
    sa.Column('cancel_reason', sa.String(length=300), nullable=True),
    sa.Column('confirmed_by_contact_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reminder_sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reminder_24h_sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reminder_2h_sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes_enc', sa.LargeBinary(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.CheckConstraint("cancelled_by IS NULL OR cancelled_by IN ('contact', 'tenant', 'system')", name=op.f('ck_appointments_cancelled_by')),
    sa.CheckConstraint("source IN ('bot', 'manual')", name=op.f('ck_appointments_source')),
    sa.CheckConstraint("status IN ('pending', 'confirmed', 'cancelled', 'no_show', 'done')", name=op.f('ck_appointments_status')),
    sa.CheckConstraint("sync_status IN ('local_only', 'synced', 'pending_push', 'failed')", name=op.f('ck_appointments_sync_status')),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], name=op.f('fk_appointments_contact_id_contacts'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['resource_id'], ['resources.id'], name=op.f('fk_appointments_resource_id_resources'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], name=op.f('fk_appointments_service_id_services'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_appointments_tenant_id_tenants'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_appointments')),
    sa.UniqueConstraint('tenant_id', 'idempotency_key', name='uq_appointments_tenant_idem')
    )
    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_appointments_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index('ix_appointments_tenant_starts', ['tenant_id', 'starts_at'], unique=False)
        batch_op.create_index('uq_appointments_active_slot', ['tenant_id', 'resource_key', 'starts_at'], unique=True, sqlite_where=sa.text("status IN ('pending', 'confirmed')"), postgresql_where=sa.text("status IN ('pending', 'confirmed')"))

    op.create_table('billing_records',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('subscription_id', sa.Uuid(), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('period', sa.String(length=7), nullable=True),
    sa.Column('amount_cop', sa.Integer(), nullable=False),
    sa.Column('iva_cop', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('method', sa.String(length=20), nullable=True),
    sa.Column('reference', sa.String(length=120), nullable=False),
    sa.Column('external_invoice_no', sa.String(length=60), nullable=True),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.CheckConstraint("kind IN ('setup', 'mensualidad', 'ajuste', 'reembolso', 'descuento')", name=op.f('ck_billing_records_kind')),
    sa.CheckConstraint("method IS NULL OR method IN ('transferencia', 'nequi', 'daviplata', 'pse', 'efectivo', 'otro')", name=op.f('ck_billing_records_method')),
    sa.CheckConstraint("status IN ('pendiente', 'pagado', 'vencido', 'anulado')", name=op.f('ck_billing_records_status')),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_billing_records_created_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['subscription_id'], ['subscriptions.id'], name=op.f('fk_billing_records_subscription_id_subscriptions'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_billing_records_tenant_id_tenants'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_billing_records'))
    )
    with op.batch_alter_table('billing_records', schema=None) as batch_op:
        batch_op.create_index('ix_billing_records_status_due', ['status', 'due_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_billing_records_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index('uq_billing_monthly', ['subscription_id', 'kind', 'period'], unique=True, sqlite_where=sa.text("kind = 'mensualidad'"), postgresql_where=sa.text("kind = 'mensualidad'"))

    op.create_table('campaigns',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('niche', sa.String(length=30), nullable=True),
    sa.Column('template_id', sa.Uuid(), nullable=True),
    sa.Column('daily_limit', sa.Integer(), nullable=False),
    sa.Column('send_window', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('audience_filter', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('stage_target', sa.String(length=20), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('paused_reason', sa.String(length=300), nullable=True),
    sa.Column('stats', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("stage_target IS NULL OR stage_target IN ('nuevo', 'prueba_secreta', 'contactado', 'demo')", name=op.f('ck_campaigns_stage_target')),
    sa.CheckConstraint("status IN ('draft', 'ready', 'running', 'paused', 'completed', 'cancelled')", name=op.f('ck_campaigns_status')),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_campaigns_created_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['template_id'], ['message_templates.id'], name=op.f('fk_campaigns_template_id_message_templates'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_campaigns'))
    )
    op.create_table('consents',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('contact_id', sa.Uuid(), nullable=False),
    sa.Column('purpose', sa.String(length=20), nullable=False),
    sa.Column('policy_version', sa.String(length=20), nullable=False),
    sa.Column('granted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('evidence', sa.Text(), nullable=False),
    sa.Column('channel', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.CheckConstraint("purpose IN ('atencion', 'recordatorios', 'marketing')", name=op.f('ck_consents_purpose')),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], name=op.f('fk_consents_contact_id_contacts'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_consents_tenant_id_tenants'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_consents'))
    )
    with op.batch_alter_table('consents', schema=None) as batch_op:
        batch_op.create_index('ix_consents_tenant_contact', ['tenant_id', 'contact_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_consents_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('conversations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('contact_id', sa.Uuid(), nullable=True),
    sa.Column('channel_account_id', sa.Uuid(), nullable=True),
    sa.Column('channel', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('last_message_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_inbound_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('summary_upto_message_id', sa.Uuid(), nullable=True),
    sa.Column('handoff_reason', sa.String(length=40), nullable=True),
    sa.Column('locale', sa.String(length=10), nullable=False),
    sa.Column('bot_paused_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.CheckConstraint("channel IN ('whatsapp', 'voice', 'sandbox', 'web')", name=op.f('ck_conversations_channel')),
    sa.CheckConstraint("status IN ('open', 'handoff', 'closed')", name=op.f('ck_conversations_status')),
    sa.ForeignKeyConstraint(['channel_account_id'], ['channel_accounts.id'], name=op.f('fk_conversations_channel_account_id_channel_accounts'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], name=op.f('fk_conversations_contact_id_contacts'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_conversations_tenant_id_tenants'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_conversations'))
    )
    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.create_index('ix_conversations_tenant_contact', ['tenant_id', 'contact_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_conversations_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index('ix_conversations_tenant_last', ['tenant_id', 'last_message_at'], unique=False)

    op.create_table('lead_events',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('lead_id', sa.Uuid(), nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('actor_user_id', sa.Uuid(), nullable=True),
    sa.Column('kind', sa.String(length=30), nullable=False),
    sa.Column('data', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.CheckConstraint("kind IN ('created', 'imported', 'scored', 'stage_changed', 'note', 'outreach_sent', 'reply_received', 'opt_out', 'secret_shop_sent', 'secret_shop_replied', 'demo_created', 'converted')", name=op.f('ck_lead_events_kind')),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], name=op.f('fk_lead_events_actor_user_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], name=op.f('fk_lead_events_lead_id_leads'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_lead_events'))
    )
    with op.batch_alter_table('lead_events', schema=None) as batch_op:
        batch_op.create_index('ix_lead_events_lead_ts', ['lead_id', 'ts'], unique=False)

    op.create_table('review_signals',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('lead_id', sa.Uuid(), nullable=False),
    sa.Column('source', sa.String(length=10), nullable=False),
    sa.Column('review_ref', sa.String(length=64), nullable=False),
    sa.Column('rating', sa.SmallInteger(), nullable=True),
    sa.Column('text_excerpt', sa.String(length=280), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('matched_patterns', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("source IN ('places', 'csv')", name=op.f('ck_review_signals_source')),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], name=op.f('fk_review_signals_lead_id_leads'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_review_signals'))
    )
    with op.batch_alter_table('review_signals', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_review_signals_lead_id'), ['lead_id'], unique=False)

    op.create_table('secret_shop_tests',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('lead_id', sa.Uuid(), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('channel', sa.String(length=20), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('scenario', sa.String(length=20), nullable=False),
    sa.Column('message_text', sa.Text(), nullable=False),
    sa.Column('first_reply_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('first_reply_excerpt', sa.String(length=280), nullable=False),
    sa.Column('response_seconds', sa.Integer(), nullable=True),
    sa.Column('after_hours', sa.Boolean(), nullable=False),
    sa.Column('outcome', sa.String(length=30), nullable=True),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("channel IN ('whatsapp', 'instagram', 'llamada', 'web_form')", name=op.f('ck_secret_shop_tests_channel')),
    sa.CheckConstraint("outcome IS NULL OR outcome IN ('sin_respuesta', 'respuesta_lenta', 'respuesta_ok', 'respuesta_con_cierre')", name=op.f('ck_secret_shop_tests_outcome')),
    sa.CheckConstraint("scenario IN ('precio', 'cita', 'horario', 'urgencia')", name=op.f('ck_secret_shop_tests_scenario')),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_secret_shop_tests_created_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], name=op.f('fk_secret_shop_tests_lead_id_leads'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_secret_shop_tests'))
    )
    with op.batch_alter_table('secret_shop_tests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_secret_shop_tests_lead_id'), ['lead_id'], unique=False)

    op.create_table('time_off',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('resource_id', sa.Uuid(), nullable=True),
    sa.Column('starts_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ends_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('reason', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['resource_id'], ['resources.id'], name=op.f('fk_time_off_resource_id_resources'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_time_off_tenant_id_tenants'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_time_off'))
    )
    with op.batch_alter_table('time_off', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_time_off_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index('ix_time_off_tenant_starts', ['tenant_id', 'starts_at'], unique=False)

    op.create_table('working_hours',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('resource_id', sa.Uuid(), nullable=True),
    sa.Column('weekday', sa.SmallInteger(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['resource_id'], ['resources.id'], name=op.f('fk_working_hours_resource_id_resources'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_working_hours_tenant_id_tenants'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_working_hours'))
    )
    with op.batch_alter_table('working_hours', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_working_hours_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index('ix_working_hours_tenant_weekday', ['tenant_id', 'weekday'], unique=False)

    op.create_table('campaign_targets',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('campaign_id', sa.Uuid(), nullable=False),
    sa.Column('lead_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], name=op.f('fk_campaign_targets_campaign_id_campaigns'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], name=op.f('fk_campaign_targets_lead_id_leads'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_campaign_targets')),
    sa.UniqueConstraint('campaign_id', 'lead_id', name='uq_campaign_targets_campaign_lead')
    )
    with op.batch_alter_table('campaign_targets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_campaign_targets_campaign_id'), ['campaign_id'], unique=False)

    op.create_table('handoffs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('conversation_id', sa.Uuid(), nullable=False),
    sa.Column('reason', sa.String(length=40), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('claimed_by', sa.Uuid(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('opened_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.CheckConstraint("reason IN ('user_request', 'low_confidence', 'out_of_scope_repeated', 'medical_urgent', 'complaint', 'injection_suspected', 'tool_failure')", name=op.f('ck_handoffs_reason')),
    sa.CheckConstraint("status IN ('open', 'claimed', 'resolved')", name=op.f('ck_handoffs_status')),
    sa.ForeignKeyConstraint(['claimed_by'], ['users.id'], name=op.f('fk_handoffs_claimed_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], name=op.f('fk_handoffs_conversation_id_conversations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_handoffs_tenant_id_tenants'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_handoffs'))
    )
    with op.batch_alter_table('handoffs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_handoffs_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index('ix_handoffs_tenant_status', ['tenant_id', 'status'], unique=False)

    op.create_table('messages',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('conversation_id', sa.Uuid(), nullable=False),
    sa.Column('direction', sa.String(length=3), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('provider_sid', sa.String(length=64), nullable=True),
    sa.Column('body_enc', sa.LargeBinary(), nullable=True),
    sa.Column('body_redacted', sa.Text(), nullable=True),
    sa.Column('media_count', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('error_code', sa.String(length=20), nullable=True),
    sa.Column('template_name', sa.String(length=100), nullable=True),
    sa.Column('window_exempt', sa.Boolean(), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('llm_usage', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('guardrail_flags', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('purge_after', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.CheckConstraint("direction IN ('in', 'out')", name=op.f('ck_messages_direction')),
    sa.CheckConstraint("role IN ('user', 'assistant', 'human_agent', 'system')", name=op.f('ck_messages_role')),
    sa.CheckConstraint("status IN ('received', 'queued', 'sent', 'delivered', 'read', 'failed', 'undelivered')", name=op.f('ck_messages_status')),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], name=op.f('fk_messages_conversation_id_conversations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_messages_tenant_id_tenants'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_messages')),
    sa.UniqueConstraint('provider_sid', name=op.f('uq_messages_provider_sid'))
    )
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.create_index('ix_messages_purge_after', ['purge_after'], unique=False)
        batch_op.create_index('ix_messages_tenant_conv_created', ['tenant_id', 'conversation_id', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_messages_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('outreach_messages',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('campaign_id', sa.Uuid(), nullable=True),
    sa.Column('lead_id', sa.Uuid(), nullable=False),
    sa.Column('channel', sa.String(length=20), nullable=False),
    sa.Column('template_name', sa.String(length=100), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('step', sa.SmallInteger(), nullable=False),
    sa.Column('idempotency_key', sa.String(length=120), nullable=True),
    sa.Column('content_variables', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('provider_sid', sa.String(length=64), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('replied_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('delivery_error_code', sa.String(length=20), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("status IN ('queued', 'sent', 'delivered', 'read', 'failed', 'replied', 'skipped')", name=op.f('ck_outreach_messages_status')),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], name=op.f('fk_outreach_messages_campaign_id_campaigns'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], name=op.f('fk_outreach_messages_lead_id_leads'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_outreach_messages')),
    sa.UniqueConstraint('idempotency_key', name='uq_outreach_messages_idem')
    )
    with op.batch_alter_table('outreach_messages', schema=None) as batch_op:
        batch_op.create_index('ix_outreach_messages_campaign_status', ['campaign_id', 'status'], unique=False)
        batch_op.create_index(batch_op.f('ix_outreach_messages_lead_id'), ['lead_id'], unique=False)
        batch_op.create_index('ix_outreach_messages_provider_sid', ['provider_sid'], unique=False)

    op.create_table('scheduled_jobs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('kind', sa.String(length=40), nullable=False),
    sa.Column('run_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('dedupe_key', sa.String(length=200), nullable=True),
    sa.Column('contact_id', sa.Uuid(), nullable=True),
    sa.Column('appointment_id', sa.Uuid(), nullable=True),
    sa.Column('locked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('locked_by', sa.String(length=80), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('next_attempt_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.CheckConstraint("kind IN ('reminder_24h', 'reminder_2h', 'confirm_request', 'followup_unbooked', 'followup_noshow', 'followup_post_visit', 'hold_expire', 'reminder', 'followup')", name=op.f('ck_scheduled_jobs_kind')),
    sa.CheckConstraint("status IN ('pending', 'running', 'done', 'failed', 'cancelled')", name=op.f('ck_scheduled_jobs_status')),
    sa.ForeignKeyConstraint(['appointment_id'], ['appointments.id'], name=op.f('fk_scheduled_jobs_appointment_id_appointments'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], name=op.f('fk_scheduled_jobs_contact_id_contacts'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_scheduled_jobs_tenant_id_tenants'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_scheduled_jobs')),
    sa.UniqueConstraint('dedupe_key', name='uq_scheduled_jobs_dedupe_key')
    )
    with op.batch_alter_table('scheduled_jobs', schema=None) as batch_op:
        batch_op.create_index('ix_scheduled_jobs_status_run_at', ['status', 'run_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_scheduled_jobs_tenant_id'), ['tenant_id'], unique=False)

    # ### end Alembic commands ###

    # --- Endurecimiento solo-Postgres (SQLite lo cubre con indices unicos + verificacion en servicio) ---
    if op.get_bind().dialect.name == "postgresql":
        op.execute("CREATE EXTENSION IF NOT EXISTS btree_gist")
        op.execute(
            "ALTER TABLE appointments ADD CONSTRAINT ex_appointments_no_overlap "
            "EXCLUDE USING gist (tenant_id WITH =, resource_key WITH =, "
            "tstzrange(starts_at, ends_at, '[)') WITH &&) "
            "WHERE (status IN ('pending', 'confirmed'))"
        )
        # audit_log es append-only: bloquea UPDATE y DELETE a nivel de base de datos.
        op.execute(
            "CREATE OR REPLACE FUNCTION audit_log_immutable() RETURNS trigger AS $$ "
            "BEGIN RAISE EXCEPTION 'audit_log es append-only'; END; $$ LANGUAGE plpgsql"
        )
        op.execute(
            "CREATE TRIGGER audit_log_no_update BEFORE UPDATE OR DELETE ON audit_log "
            "FOR EACH ROW EXECUTE FUNCTION audit_log_immutable()"
        )


def downgrade() -> None:
    if op.get_bind().dialect.name == "postgresql":
        op.execute("DROP TRIGGER IF EXISTS audit_log_no_update ON audit_log")
        op.execute("DROP FUNCTION IF EXISTS audit_log_immutable()")
        op.execute("ALTER TABLE appointments DROP CONSTRAINT IF EXISTS ex_appointments_no_overlap")
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scheduled_jobs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_scheduled_jobs_tenant_id'))
        batch_op.drop_index('ix_scheduled_jobs_status_run_at')

    op.drop_table('scheduled_jobs')
    with op.batch_alter_table('outreach_messages', schema=None) as batch_op:
        batch_op.drop_index('ix_outreach_messages_provider_sid')
        batch_op.drop_index(batch_op.f('ix_outreach_messages_lead_id'))
        batch_op.drop_index('ix_outreach_messages_campaign_status')

    op.drop_table('outreach_messages')
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_messages_tenant_id'))
        batch_op.drop_index('ix_messages_tenant_conv_created')
        batch_op.drop_index('ix_messages_purge_after')

    op.drop_table('messages')
    with op.batch_alter_table('handoffs', schema=None) as batch_op:
        batch_op.drop_index('ix_handoffs_tenant_status')
        batch_op.drop_index(batch_op.f('ix_handoffs_tenant_id'))

    op.drop_table('handoffs')
    with op.batch_alter_table('campaign_targets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_campaign_targets_campaign_id'))

    op.drop_table('campaign_targets')
    with op.batch_alter_table('working_hours', schema=None) as batch_op:
        batch_op.drop_index('ix_working_hours_tenant_weekday')
        batch_op.drop_index(batch_op.f('ix_working_hours_tenant_id'))

    op.drop_table('working_hours')
    with op.batch_alter_table('time_off', schema=None) as batch_op:
        batch_op.drop_index('ix_time_off_tenant_starts')
        batch_op.drop_index(batch_op.f('ix_time_off_tenant_id'))

    op.drop_table('time_off')
    with op.batch_alter_table('secret_shop_tests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_secret_shop_tests_lead_id'))

    op.drop_table('secret_shop_tests')
    with op.batch_alter_table('review_signals', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_review_signals_lead_id'))

    op.drop_table('review_signals')
    with op.batch_alter_table('lead_events', schema=None) as batch_op:
        batch_op.drop_index('ix_lead_events_lead_ts')

    op.drop_table('lead_events')
    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.drop_index('ix_conversations_tenant_last')
        batch_op.drop_index(batch_op.f('ix_conversations_tenant_id'))
        batch_op.drop_index('ix_conversations_tenant_contact')

    op.drop_table('conversations')
    with op.batch_alter_table('consents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_consents_tenant_id'))
        batch_op.drop_index('ix_consents_tenant_contact')

    op.drop_table('consents')
    op.drop_table('campaigns')
    with op.batch_alter_table('billing_records', schema=None) as batch_op:
        batch_op.drop_index('uq_billing_monthly', sqlite_where=sa.text("kind = 'mensualidad'"), postgresql_where=sa.text("kind = 'mensualidad'"))
        batch_op.drop_index(batch_op.f('ix_billing_records_tenant_id'))
        batch_op.drop_index('ix_billing_records_status_due')

    op.drop_table('billing_records')
    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.drop_index('uq_appointments_active_slot', sqlite_where=sa.text("status IN ('pending', 'confirmed')"), postgresql_where=sa.text("status IN ('pending', 'confirmed')"))
        batch_op.drop_index('ix_appointments_tenant_starts')
        batch_op.drop_index(batch_op.f('ix_appointments_tenant_id'))

    op.drop_table('appointments')
    with op.batch_alter_table('usage_counters', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_usage_counters_tenant_id'))

    op.drop_table('usage_counters')
    with op.batch_alter_table('tenant_secrets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tenant_secrets_tenant_id'))

    op.drop_table('tenant_secrets')
    op.drop_table('tenant_profiles')
    with op.batch_alter_table('subscriptions', schema=None) as batch_op:
        batch_op.drop_index('ix_subscriptions_tenant_status')
        batch_op.drop_index(batch_op.f('ix_subscriptions_tenant_id'))

    op.drop_table('subscriptions')
    with op.batch_alter_table('services', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_services_tenant_id'))
        batch_op.drop_index('ix_services_tenant_active')

    op.drop_table('services')
    with op.batch_alter_table('resources', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_resources_tenant_id'))

    op.drop_table('resources')
    with op.batch_alter_table('message_templates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_message_templates_tenant_id'))

    op.drop_table('message_templates')
    with op.batch_alter_table('llm_usage', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_llm_usage_tenant_id'))
        batch_op.drop_index('ix_llm_usage_tenant_created')

    op.drop_table('llm_usage')
    with op.batch_alter_table('leads', schema=None) as batch_op:
        batch_op.drop_index('uq_leads_phone_hash_active', sqlite_where=sa.text("phone_hash IS NOT NULL AND disposition <> 'perdido'"), postgresql_where=sa.text("phone_hash IS NOT NULL AND disposition <> 'perdido'"))
        batch_op.drop_index('ix_leads_website_domain')
        batch_op.drop_index('ix_leads_stage_score')
        batch_op.drop_index('ix_leads_niche_city')
        batch_op.drop_index('ix_leads_name_key')

    op.drop_table('leads')
    with op.batch_alter_table('kb_documents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_kb_documents_tenant_id'))

    op.drop_table('kb_documents')
    with op.batch_alter_table('faqs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_faqs_tenant_id'))

    op.drop_table('faqs')
    with op.batch_alter_table('contacts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_contacts_tenant_id'))

    op.drop_table('contacts')
    with op.batch_alter_table('channel_accounts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_channel_accounts_tenant_id'))

    op.drop_table('channel_accounts')
    with op.batch_alter_table('calendar_connections', schema=None) as batch_op:
        batch_op.drop_index('uq_calendar_connections_active', sqlite_where=sa.text("status <> 'revoked'"), postgresql_where=sa.text("status <> 'revoked'"))
        batch_op.drop_index(batch_op.f('ix_calendar_connections_tenant_id'))

    op.drop_table('calendar_connections')
    with op.batch_alter_table('bot_configs', schema=None) as batch_op:
        batch_op.drop_index('uq_bot_configs_one_published', sqlite_where=sa.text("status = 'published'"), postgresql_where=sa.text("status = 'published'"))
        batch_op.drop_index(batch_op.f('ix_bot_configs_tenant_id'))

    op.drop_table('bot_configs')
    with op.batch_alter_table('tenants', schema=None) as batch_op:
        batch_op.drop_index('ix_tenants_status')

    op.drop_table('tenants')
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.drop_index('ix_sessions_user_id')
        batch_op.drop_index('ix_sessions_expires_at')

    op.drop_table('sessions')
    op.drop_table('lead_sources')
    with op.batch_alter_table('webhook_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_webhook_events_tenant_id'))

    op.drop_table('webhook_events')
    op.drop_table('users')
    with op.batch_alter_table('suppression_list', schema=None) as batch_op:
        batch_op.drop_index('uq_suppression_phone_scope')
        batch_op.drop_index(batch_op.f('ix_suppression_list_phone_hash'))

    op.drop_table('suppression_list')
    op.drop_table('plans')
    op.drop_table('offers')
    with op.batch_alter_table('niche_templates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_niche_templates_niche'))

    op.drop_table('niche_templates')
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.drop_index('ix_audit_log_ts')
        batch_op.drop_index('ix_audit_log_tenant_id')
        batch_op.drop_index('ix_audit_log_action')

    op.drop_table('audit_log')
    # ### end Alembic commands ###
