"""indices_unicos_parciales

Revision ID: 0003
Revises: 0002
Create Date: 2026-10-09 02:30:24.764797
"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql


revision: str = '0003'
down_revision: str | None = '0002'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('billing_records', schema=None) as batch_op:
        batch_op.create_index('ix_billing_records_sub_status', ['subscription_id', 'status'], unique=False)

    with op.batch_alter_table('consents', schema=None) as batch_op:
        batch_op.create_index('uq_consents_active', ['tenant_id', 'contact_id', 'purpose'], unique=True, sqlite_where=sa.text('revoked_at IS NULL'), postgresql_where=sa.text('revoked_at IS NULL'))

    with op.batch_alter_table('handoffs', schema=None) as batch_op:
        batch_op.create_index('uq_handoffs_active_conversation', ['conversation_id'], unique=True, sqlite_where=sa.text("status IN ('open', 'claimed')"), postgresql_where=sa.text("status IN ('open', 'claimed')"))

    with op.batch_alter_table('scheduled_jobs', schema=None) as batch_op:
        batch_op.create_index('ix_scheduled_jobs_tenant_status_run', ['tenant_id', 'status', 'run_at'], unique=False)

    with op.batch_alter_table('subscriptions', schema=None) as batch_op:
        batch_op.create_index('uq_subscriptions_tenant_live', ['tenant_id'], unique=True, sqlite_where=sa.text("status != 'cancelled'"), postgresql_where=sa.text("status != 'cancelled'"))

    with op.batch_alter_table('time_off', schema=None) as batch_op:
        batch_op.create_index('ix_time_off_tenant_ends', ['tenant_id', 'ends_at'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('time_off', schema=None) as batch_op:
        batch_op.drop_index('ix_time_off_tenant_ends')

    with op.batch_alter_table('subscriptions', schema=None) as batch_op:
        batch_op.drop_index('uq_subscriptions_tenant_live', sqlite_where=sa.text("status != 'cancelled'"), postgresql_where=sa.text("status != 'cancelled'"))

    with op.batch_alter_table('scheduled_jobs', schema=None) as batch_op:
        batch_op.drop_index('ix_scheduled_jobs_tenant_status_run')

    with op.batch_alter_table('handoffs', schema=None) as batch_op:
        batch_op.drop_index('uq_handoffs_active_conversation', sqlite_where=sa.text("status IN ('open', 'claimed')"), postgresql_where=sa.text("status IN ('open', 'claimed')"))

    with op.batch_alter_table('consents', schema=None) as batch_op:
        batch_op.drop_index('uq_consents_active', sqlite_where=sa.text('revoked_at IS NULL'), postgresql_where=sa.text('revoked_at IS NULL'))

    with op.batch_alter_table('billing_records', schema=None) as batch_op:
        batch_op.drop_index('ix_billing_records_sub_status')

    # ### end Alembic commands ###
