"""pagos_y_voz

Revision ID: 0004
Revises: 0003
Create Date: 2026-10-09 03:05:06.102179
"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql


revision: str = '0004'
down_revision: str | None = '0003'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('call_sessions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('call_sid', sa.String(length=64), nullable=False),
    sa.Column('conversation_id', sa.Uuid(), nullable=True),
    sa.Column('turns', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('consent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.CheckConstraint("status IN ('active', 'transferred', 'completed', 'rejected')", name=op.f('ck_call_sessions_status')),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], name=op.f('fk_call_sessions_conversation_id_conversations'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_call_sessions_tenant_id_tenants'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_call_sessions')),
    sa.UniqueConstraint('call_sid', name='uq_call_sessions_call_sid')
    )
    with op.batch_alter_table('call_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_call_sessions_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('payment_intents',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('billing_record_id', sa.Uuid(), nullable=False),
    sa.Column('reference', sa.String(length=100), nullable=False),
    sa.Column('provider', sa.String(length=20), nullable=False),
    sa.Column('amount_cop', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('link_url', sa.Text(), nullable=True),
    sa.Column('provider_tx_id', sa.String(length=100), nullable=True),
    sa.Column('raw_last_event', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("status IN ('pending', 'approved', 'declined', 'voided', 'error')", name=op.f('ck_payment_intents_status')),
    sa.ForeignKeyConstraint(['billing_record_id'], ['billing_records.id'], name=op.f('fk_payment_intents_billing_record_id_billing_records'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_payment_intents')),
    sa.UniqueConstraint('reference', name=op.f('uq_payment_intents_reference'))
    )
    with op.batch_alter_table('payment_intents', schema=None) as batch_op:
        batch_op.create_index('ix_payment_intents_billing_record', ['billing_record_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payment_intents', schema=None) as batch_op:
        batch_op.drop_index('ix_payment_intents_billing_record')

    op.drop_table('payment_intents')
    with op.batch_alter_table('call_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_call_sessions_tenant_id'))

    op.drop_table('call_sessions')
    # ### end Alembic commands ###
